use super::*;

pub(super) fn buf_sphere_params() -> Vec<NodeParamSlot> {
    vec![
        param(
            param_schema::sphere_buffer::RADIUS,
            "radius",
            0.28,
            0.02,
            0.5,
            0.005,
        ),
        param(
            param_schema::sphere_buffer::SEGMENTS,
            "segments",
            32.0,
            3.0,
            128.0,
            1.0,
        ),
        param(
            param_schema::sphere_buffer::RINGS,
            "rings",
            16.0,
            2.0,
            64.0,
            1.0,
        ),
    ]
}

pub(super) fn buf_circle_nurbs_params() -> Vec<NodeParamSlot> {
    vec![
        param(
            param_schema::circle_nurbs_buffer::RADIUS,
            "radius",
            0.28,
            0.02,
            0.95,
            0.005,
        ),
        param(
            param_schema::circle_nurbs_buffer::ARC_START,
            "arc_start",
            0.0,
            0.0,
            360.0,
            1.0,
        ),
        param(
            param_schema::circle_nurbs_buffer::ARC_END,
            "arc_end",
            360.0,
            0.0,
            360.0,
            1.0,
        ),
        param(
            param_schema::circle_nurbs_buffer::LINE_WIDTH,
            "line_width",
            0.01,
            0.0005,
            0.35,
            0.001,
        ),
        param(
            param_schema::circle_nurbs_buffer::ORDER,
            "order",
            3.0,
            2.0,
            5.0,
            1.0,
        ),
        param(
            param_schema::circle_nurbs_buffer::DIVISIONS,
            "divisions",
            64.0,
            8.0,
            512.0,
            1.0,
        ),
        param_dropdown(
            param_schema::circle_nurbs_buffer::ARC_STYLE,
            "arc_style",
            0,
            &BUF_CIRCLE_ARC_STYLE_OPTIONS,
        ),
    ]
}

pub(super) fn buf_noise_params() -> Vec<NodeParamSlot> {
    vec![
        // Keep deformation disabled by default so inserting this node is
        // identity until users increase amplitude.
        param(
            param_schema::buffer_noise::AMPLITUDE,
            "amplitude",
            0.0,
            0.0,
            1.0,
            0.01,
        ),
        param(
            param_schema::buffer_noise::FREQUENCY,
            "frequency",
            2.0,
            0.05,
            32.0,
            0.05,
        ),
        param(
            param_schema::buffer_noise::SPEED_HZ,
            "speed_hz",
            0.35,
            0.0,
            16.0,
            0.05,
        ),
        param(
            param_schema::buffer_noise::PHASE,
            "phase",
            0.0,
            -8.0,
            8.0,
            0.05,
        ),
        param(
            param_schema::buffer_noise::SEED,
            "seed",
            1.0,
            0.0,
            1024.0,
            1.0,
        ),
        param(
            param_schema::buffer_noise::TWIST,
            "twist",
            0.0,
            -8.0,
            8.0,
            0.05,
        ),
        param(
            param_schema::buffer_noise::STRETCH,
            "stretch",
            0.0,
            0.0,
            1.0,
            0.01,
        ),
        // Loop mode quantizes time to timeline phase for clean first/last
        // frame matching and deterministic clip playback.
        param(
            param_schema::buffer_noise::LOOP_CYC,
            "loop_cyc",
            12.0,
            0.0,
            256.0,
            1.0,
        ),
        param_dropdown(
            param_schema::buffer_noise::LOOP_MODE,
            "loop_mode",
            0,
            &BUF_NOISE_LOOP_MODE_OPTIONS,
        ),
    ]
}
