//! Shader module loading for WGSL and rust-gpu SPIR-V backends.
//!
//! The runtime defaults to WGSL for compatibility. Set
//! `COVERGEN_SHADER_BACKEND=rust-gpu` to load SPIR-V artifacts generated by a
//! rust-gpu toolchain.

use std::borrow::Cow;
use std::error::Error;
use std::path::{Path, PathBuf};

/// Shader programs used by the runtime.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub(crate) enum ShaderProgram {
    FractalMain,
    GraphOps,
    GraphDecode,
    RetainedPost,
}

#[derive(Clone, Copy, Debug, PartialEq, Eq)]
enum ShaderBackend {
    Wgsl,
    RustGpu,
}

const SHADER_BACKEND_ENV: &str = "COVERGEN_SHADER_BACKEND";
const SHADER_SPIRV_DIR_ENV: &str = "COVERGEN_RUST_GPU_SPIRV_DIR";

const FRACTAL_WGSL: &str = include_str!(concat!(env!("CARGO_MANIFEST_DIR"), "/src/shader.wgsl"));
const GRAPH_OPS_WGSL: &str = include_str!(concat!(
    env!("CARGO_MANIFEST_DIR"),
    "/src/gpu_graph_ops.wgsl"
));
const GRAPH_DECODE_WGSL: &str = include_str!(concat!(
    env!("CARGO_MANIFEST_DIR"),
    "/src/gpu_graph_decode.wgsl"
));
const RETAINED_POST_WGSL: &str = include_str!(concat!(
    env!("CARGO_MANIFEST_DIR"),
    "/src/gpu_retained_post.wgsl"
));

/// Create a shader module for the requested program using the configured backend.
pub(crate) fn create_shader_module(
    device: &wgpu::Device,
    program: ShaderProgram,
) -> Result<wgpu::ShaderModule, Box<dyn Error>> {
    match shader_backend_from_env() {
        ShaderBackend::Wgsl => Ok(device.create_shader_module(wgpu::ShaderModuleDescriptor {
            label: Some(program_label(program)),
            source: wgpu::ShaderSource::Wgsl(Cow::Borrowed(program_wgsl(program))),
        })),
        ShaderBackend::RustGpu => {
            let words = load_spirv_words(program)?;
            Ok(device.create_shader_module(wgpu::ShaderModuleDescriptor {
                label: Some(program_label(program)),
                source: wgpu::ShaderSource::SpirV(Cow::Owned(words)),
            }))
        }
    }
}

fn shader_backend_from_env() -> ShaderBackend {
    let Ok(raw) = std::env::var(SHADER_BACKEND_ENV) else {
        return ShaderBackend::Wgsl;
    };
    match raw.trim().to_ascii_lowercase().as_str() {
        "rust-gpu" | "rust_gpu" | "spirv" => ShaderBackend::RustGpu,
        _ => ShaderBackend::Wgsl,
    }
}

fn program_label(program: ShaderProgram) -> &'static str {
    match program {
        ShaderProgram::FractalMain => "fractal shader",
        ShaderProgram::GraphOps => "v2 graph ops shader",
        ShaderProgram::GraphDecode => "v2 graph decode shader",
        ShaderProgram::RetainedPost => "retained post shader",
    }
}

fn program_wgsl(program: ShaderProgram) -> &'static str {
    match program {
        ShaderProgram::FractalMain => FRACTAL_WGSL,
        ShaderProgram::GraphOps => GRAPH_OPS_WGSL,
        ShaderProgram::GraphDecode => GRAPH_DECODE_WGSL,
        ShaderProgram::RetainedPost => RETAINED_POST_WGSL,
    }
}

fn program_spirv_name(program: ShaderProgram) -> &'static str {
    match program {
        ShaderProgram::FractalMain => "fractal_main.spv",
        ShaderProgram::GraphOps => "graph_ops.spv",
        ShaderProgram::GraphDecode => "graph_decode.spv",
        ShaderProgram::RetainedPost => "retained_post.spv",
    }
}

fn load_spirv_words(program: ShaderProgram) -> Result<Vec<u32>, Box<dyn Error>> {
    let file = program_spirv_name(program);
    let path = spirv_root_dir().join(file);
    let bytes = std::fs::read(&path).map_err(|err| {
        format!(
            "failed to read rust-gpu SPIR-V '{}' at {}: {err}",
            file,
            path.display()
        )
    })?;
    parse_spirv_words(&bytes, &path)
}

fn spirv_root_dir() -> PathBuf {
    if let Ok(path) = std::env::var(SHADER_SPIRV_DIR_ENV) {
        return PathBuf::from(path);
    }
    PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("target/rust-gpu")
}

fn parse_spirv_words(bytes: &[u8], path: &Path) -> Result<Vec<u32>, Box<dyn Error>> {
    if bytes.len() < 4 || bytes.len() % 4 != 0 {
        return Err(format!(
            "invalid SPIR-V byte length for {}: expected multiple of 4, got {}",
            path.display(),
            bytes.len()
        )
        .into());
    }

    let mut words = Vec::with_capacity(bytes.len() / 4);
    for chunk in bytes.chunks_exact(4) {
        words.push(u32::from_le_bytes([chunk[0], chunk[1], chunk[2], chunk[3]]));
    }

    const SPIRV_MAGIC: u32 = 0x0723_0203;
    if words.first().copied() != Some(SPIRV_MAGIC) {
        return Err(format!(
            "invalid SPIR-V magic in {}: expected {SPIRV_MAGIC:#x}",
            path.display()
        )
        .into());
    }

    Ok(words)
}
